name: 'Hide pull request comments action'
description: 'Hide PR comments by given condition'
inputs:
  github_token:
    description: 'Access token of GitHub'
    required: true
    default: ${{ github.token }}
  author:
    description: 'Username of author'
    required: false
  message_regex:
    description: 'Regexp of comment'
    required: false
  pr_number:
    description: 'Number of pull request. Must be set if event_type is not pull_requset'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
