on:
  push:
    branches-ignore:
      - 'main'
jobs:
  test-and-release:
    runs-on: ubuntu-latest
    name: Continuous integration
    steps:
      - uses: actions/checkout@v2
      - name: Comment PR 1
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "This message is posted by a human, should not be hidden [push]"
          check_for_duplicate_msg: false
      - name: Comment PR 2
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "This message is posted by a bot, should be hidden [push]"
          check_for_duplicate_msg: false
      - name: Get PR number
        id: pr_number
        run: echo "::set-output name=pr_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run action
        id: action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author: github-actions
          message_regex: should be hidden \[push\]$
          pr_number: ${{ steps.pr_number.outputs.pr_number }}
