on:
  pull_request:
jobs:
  test-and-release:
    runs-on: ubuntu-latest
    name: Continuous integration
    steps:
    - uses: actions/checkout@v2
    - name: Comment PR 1
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "This message is posted by a human, should not be hidden [pull_request]"
        check_for_duplicate_msg: false
    - name: Comment PR 2
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "This message is posted by a bot, should be hidden [pull_request]"
        check_for_duplicate_msg: false
    - name: Run action
      id: action
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        author: github-actions
        message_regex: should be hidden \[pull_request\]$
